### ISSUE TITLE
Розминка

### ISSUE THREAD

**Issue by zoriana-melnyk** [olehtsyb/okeyy_team_repository#4]
Створити тест для розминки

**Comment by zoriana-melnyk** [comment]
А якщо гру "Вірю-не вірю" провести у якості розминки? Замість тесту

**Comment by olehtsyb** [comment]
Звучить добре, займусь цим

**Comment by olehtsyb** [comment]
Назначив завдання "Вірю - Не вірю" як завдання для розминки
